export const accountDetailsEN = {
    heroTitle: 'Personal info',
    heroText: 'Update your personal details here.',
    firstName: 'First name',
    lastName: 'Last name',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    changePassword: 'Change password',
    emailAddress: 'Email address',
    phoneNumber: 'Phone number',
    locale: 'Locale',
    selectLocale: 'Select locale',
    addresses: 'Addresses',
    edit: 'Edit',
    addNewAddress: 'Add new address',
    country: 'Country',
    city: 'City',
    county: 'County',
    postalCode: 'Postal code',
    street: 'Street',
    submitAddress: 'Submit address',
    saveChanges: 'Save changes',
    cancel: 'Cancel',
    companies: 'Companies',
    compnayCheck: 'Are you representing a company?',
    save: 'Save cahnges',
    companyName: 'Company name',
    companyCode: 'Company code',
    hu: 'Hungarian (HU)',
    ro: 'Romanian (RO)',
    en: 'English (EN)',
    address: 'Address',
    updateAddress: 'Update address',
    updateCompany: 'Update company',
    submitCompany: 'Submit company',
    addNewCompany: 'Add new company',
    accountDetails: 'Account details',
    orderHistory: 'Order history',
    logout: 'Logout',
};