export const accountDetailsHU = {
    heroTitle: 'Személyes adatok',
    heroText: 'Itt frissítheted a személyes adataidat.',
    firstName: 'Keresztnév',
    lastName: 'Vezetéknév',
    name: 'Név',
    email: 'Email',
    password: 'Jelszó',
    changePassword: 'Jelszó megváltoztatása',
    emailAddress: 'Email cím',
    phoneNumber: 'Telefonszám',
    locale: 'Nyelv',
    selectLocale: 'Nyelv kiválasztása',
    addresses: 'Címek',
    edit: 'Szerkesztés',
    addNewAddress: 'Új cím hozzáadása',
    country: 'Ország',
    city: 'Város',
    county: 'Megye',
    postalCode: 'Irányítószám',
    street: 'Utca',
    submitAddress: 'Cím benyújtása',
    saveChanges: 'Változtatások mentése',
    cancel: 'Mégsem',
    companies: 'Cégek',
    companyCheck: 'Céget képvisel?',
    save: 'Változtatások mentése',
    companyName: 'Cég neve',
    companyCode: 'Cégkód',
    hu: 'Magyar (HU)',
    ro: 'Román (RO)',
    en: 'Angol (EN)',
    address: 'Cím',
    updateAddress: 'Cím frissítése',
    updateCompany: 'Cég frissítése',
    submitCompany: 'Cég hozzáadása',
    addNewCompany: 'Új cég hozzáadása',
    accountDetails: 'Fiók adatok',
    orderHistory: 'Rendelési előzmények',
    logout: 'Kijelentkezés',
};
