export const accountDetailsRO = {
    heroTitle: 'Informații personale',
    heroText: 'Actualizați detaliile dumneavoastră personale aici.',
    firstName: 'Nume',
    lastName: 'Prenume',
    name: 'Nume',
    email: 'Email',
    password: 'Parolă',
    changePassword: 'Schimbă parola',
    emailAddress: 'Adresă de email',
    phoneNumber: 'Număr de telefon',
    locale: 'Limba',
    selectLocale: 'Selectează limba',
    addresses: 'Adrese',
    edit: 'Editează',
    addNewAddress: 'Adaugă o adresă nouă',
    country: 'Țară',
    city: 'Oraș',
    county: 'Județ',
    postalCode: 'Cod poștal',
    street: 'Stradă',
    submitAddress: 'Trimite adresa',
    saveChanges: 'Salvează modificările',
    cancel: 'Anulează',
    companies: 'Companii',
    compnayCheck: 'Reprezentați o companie?',
    save: 'Salvează modificările',
    companyName: 'Numele companiei',
    companyCode: 'Codul companiei',
    hu: 'Maghiară (HU)',
    ro: 'Română (RO)',
    en: 'Engleză (EN)',
    address: 'Adresă',
    updateAddress: 'Actualizează adresa',
    updateCompany: 'Actualizează compania',
    submitCompany: 'Trimite compania',
    addNewCompany: 'Adaugă o companie nouă',
    accountDetails: 'Detalii cont',
    orderHistory: 'Istoricul comenzilor',
    logout: 'Deconectare',
};
